name: Notify Teams on Commit and Deploy

on:
  push:
    branches:
      - main  # O tu rama principal
  workflow_run:
    workflows: ["Firebase Deploy"]  # nombre de tu workflow de deploy si tienes uno

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        run: |
          curl -H 'Content-Type: application/json' \
               -d '{
                 "text": "🚀 Se hizo un push a la rama main del proyecto React. Revisa el estado del deploy."
               }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
